# https://ridbay.medium.com/how-to-deploy-private-github-repositories-to-cpanel-ef5493df8d9f
name: Build and Deploy to CPanel
on:
  push:
    branches:
      - main
jobs:
  ftp-deploy-action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          #branch: build
          #folder: build
          local-dir: ./build/
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: true
